@startuml
left to right direction

object HmiInput
object CooktopController
object SafetyManager
object PowerControl
object HmiOutput

HmiInput -> CooktopController : 1. increasePower(zoneID)
CooktopController -> SafetyManager : 2. isLocked()
CooktopController -> PowerControl : 3. increaseLevel(zoneID)
CooktopController -> HmiOutput : 4. showPowerLevel(zoneID, neueStufe)

note bottom of CooktopController
3.1 neueStufe (von PowerControl)
end note

@enduml
